### ISSUE TITLE
Не работает с  WebRTC 3.x.x

### ISSUE THREAD

**Issue by AlexeyTorch** [alryaz/hass-pik-intercom#18]
при попытке подключить карточку в lovelease
```
          - type: horizontal-stack
            cards:
              - type: 'custom:webrtc-camera'
                entity: camera.iot_relay_53401
              - type: 'custom:webrtc-camera'
                entity: camera.iot_relay_53400

          - type: horizontal-stack
            cards:
              - type: 'custom:webrtc-camera'
                entity: camera.iot_relay_53457
```

возникает ошибка
**mse: source 0 error: wrong response on Describe.**
![Screenshot 2023-01-30 121839](https://user-images.githubusercontent.com/64954625/215436591-8b43db79-b39c-48d3-91d9-46c57b3304bd.png)

Ощибка была на бетах Webrtc 3, на 3.0.0, 3.0.1

**Comment by ofilin** [comment]
подтверждаю, такая же проблема

**Comment by cpsskipper** [comment]
та же проблема

**Comment by Napalmcold** [comment]
Аналогично

**Comment by ofilin** [comment]
В общем сделал костыль, не разбирался глубоко в чем проблема, но решил её так:
```
type: custom:card-templater
card:
  type: custom:webrtc-camera
  url_template: ffmpeg:{{ state_attr("camera.vp_1_2_intercom","stream_url") }}
  shortcuts:
    - name: Open
      icon: mdi:lock-open-variant
      service: button.press
      service_data:
        entity_id: button.vp_1_2_unlocker
entities:
  - camera.vp_1_2_intercom
```
таким образом в WebRTC передается url не rtsp://v.intercom.pik-comfort.ru:34567, а **ffmpeg:**rtsp://v.intercom.pik-comfort.ru:34567 т.е. мы говорим, что поток должен обрабатываться через ffmpeg, картинка появилась, все ОК
Дополнительно необходимо установить lovelace-card-templater, что-бы можно было конкатенировать ffmpeg:RTSP_URL: https://github.com/gadgetchnnel/lovelace-card-templater

**Comment by cpsskipper** [comment]
Отлично, заработало!
Единственно нагрузка на процессор подросла.

**Comment by Angry0209** [comment]
> В общем сделал костыль, не разбирался глубоко в чем проблема, но решил её так:
> 
> ```
> type: custom:card-templater
> card:
>   type: custom:webrtc-camera
>   url_template: ffmpeg:{{ state_attr("camera.vp_1_2_intercom","stream_url") }}
>   shortcuts:
>     - name: Open
>       icon: mdi:lock-open-variant
>       service: button.press
>       service_data:
>         entity_id: button.vp_1_2_unlocker
> entities:
>   - camera.vp_1_2_intercom
> ```
> 
> таким образом в WebRTC передается url не rtsp://v.intercom.pik-comfort.ru:34567, а ffmpeg:rtsp://v.intercom.pik-comfort.ru:34567 т.е. мы говорим, что поток должен обрабатываться через ffmpeg, картинка появилась, все ОК Дополнительно необходимо установить lovelace-card-templater, что-бы можно было конкатенировать ffmpeg:RTSP_URL: https://github.com/gadgetchnnel/lovelace-card-templater
> 
> Напишите, если кому помогло

Не помогло, или не правильно настроил. 
Не пойму что делать с "stream_url", менять на что то или так оставляем?
![Снимок экрана 2024-02-29 100049](https://github.com/alryaz/hass-pik-intercom/assets/147315598/19322398-4d8b-4592-afbb-bd3935b86ae8)
оил.

**Comment by ofilin** [comment]
Вы бы скинули код, который используете, тогда было бы видно...

**Comment by Angry0209** [comment]
> Вы бы скинули код, который используете, тогда было бы видно...

type: custom:card-templater
card:
  type: custom:webrtc-camera
  url_template: ffmpeg:{{ state_attr("camera.bp_4_9_1_intercom","stream_url") }}
  shortcuts:
    - name: Open
      icon: mdi:lock-open-variant
      service: button.press
      service_data:
        entity_id: button.1_9_2_kd_1_0_1_unlocker
entities:
  - camera.bp_4_9_1_intercom

**Comment by ofilin** [comment]
Сделайте так:
```
type: custom:card-templater
card:
  type: custom:webrtc-camera
  url_template: ffmpeg:{{ state_attr("camera.bp_4_9_1_intercom","stream_url") }}
entities:
  - camera.bp_4_9_1_intercom
```
после сохранения зайдите в интеграции /config/integrations/integration/pik_intercom и перезапустите **PIK Intercom / ПИК Домофон**, и только после перезагрузки интеграции проверьте, работает видео или нет
